---
- name: Bootstrap Main Node
  hosts: main
  become: yes       # sudo user
  
  tasks: 
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: add grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: update apt cache and install grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: ensure grafana is started and enabled
    ansible.builtin.service:
      state: started
      enabled: yes
      name: grafana-server
  - name: download prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
  - name: extract prometheus resources
    ansible.builtin.unarchive:
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
      remote_src: yes
  - name: create prometheus group
    ansible.builtin.group:
      name: prometheus
      state: present
  - name: create prometheus user
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin
  # - name: create prometheus directories
  # - name: setting permissions
  # - name: copy files v1
  # - name: copy files v2
  # - name: create config file
  # - name: create systemd file
  # - name: ensure prometheus is started
    