---
- name: Bootstrap Main Node
  hosts: main
  become: yes       # sudo user
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090
  
  tasks: 
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: add grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: update apt cache and install grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: ensure grafana is started and enabled
    ansible.builtin.service:
      state: started
      enabled: yes
      name: grafana-server
  - name: download prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
  - name: extract prometheus resources
    ansible.builtin.unarchive:
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
      remote_src: yes
  - name: create prometheus group
    ansible.builtin.group:
      name: prometheus
      state: present
  - name: create prometheus user
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin
  - name: create prometheus directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes      # wil create directories recursively
      owner: prometheus
      group: prometheus
      mode: '0755'
    loop:
      - /etc/prometheus
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - /var/lib/prometheus
  - name: copy files v1
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      remote_src: yes
      mode: '0755'
      owner: prometheus
      group: prometheus
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool
  - name: copy files v2
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/prometheus
      remote_src: yes
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries
  - name: create config file
    ansible.builtin.template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
  - name: create systemd file
    ansible.builtin.template:
      src: prometheus.service.j2
      dest: /etc/systemd/system/prometheus.service
  - name: ensure prometheus is started
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: prometheus
    
    